version: "3.7"
services:
  elastic-search:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.8.1"
    container_name: "elastic-search"
    environment:
    - discovery.type=single-node
    - http.publish_host=_local_
    - indices.query.bool.max_clause_count=4046
    ports:
    - "9200:9200"
    - "9300:9300"