on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install node v12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: restore
      run: cd StationWalk.Server/Client && npm ci
    - name: eslint
      run: cd StationWalk.Server/Client && npm run lint