on:
  push:
    branches: [ package-test ]
  pull_request:
    branches: [ master ]

jobs:
  package:
    name: package
    runs-on: ubuntu-latest
    env:
      STATIONWALK_MAPBOX_TOKEN: ${{ secrets.STATIONWALK_MAPBOX_TOKEN }}
      STATIONWALK_GRAPHHOPPER_HOST: ${{ secrets.STATIONWALK_GRAPHHOPPER_HOST }}
      STATIONWALK_GRAPHHOPPER_KEY: ${{ secrets.STATIONWALK_GRAPHHOPPER_KEY }}
    steps:
    - uses: actions/checkout@v2
    - name: install node v12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: publish
      run: cd StationWalk.Server && dotnet publish "StationWalk.Server.fsproj" -c Release
    - name: zip files
      run: cd StationWalk.Server/bin/Release/net5.0/publish && zip -P ${{secrets.STATIONWALK_ARTIFACT_PASS}} -r stationwalk.zip .
    - name: create artifact
      uses: actions/upload-artifact@v2
      with:
        path: 'StationWalk.Server/bin/Release/net5.0/publish/stationwalk.zip'
        retention-days: 1